development:
  secret_key_base: bd2310bdd32ab46884e4a2b0096f33ec8d0b75486155d87d44020cc83f726febec2fbe04a0282797415950eb6994aacbeca2a5717318bc5f03262df3c69390b8

test:
  secret_key_base: 673f37306085824ce1054d8fb2702f971d4e8326ded7ff3eb6c89774ddd3b0b68308a810a6af90460fb6de8a4b7c26bf6f53d14e7a0f8e3902d59dd310c71f1a

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
